POST http://localhost:3000/users/
Content-Type: application/json

{    
    "username": "rahul123",
    "password": "rahul@456",
    "gender":"male",
    "location":"hyderabad"
}

###

POST http://localhost:3000/login/
Content-Type: application/json

{    
    "username": "rahul124",
    "password": "rahul@456"
}


###
GET http://localhost:3000/books/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTI0IiwiaWF0IjoxNjI0Njk0NjY0fQ.TXkMmjfF_D2_wI6-LATnqlahgoVipZClHlgE6kLsM7o
